### ISSUE TITLE
Can this project work?

### ISSUE THREAD

**Issue by aofei** [Doridian/wsvpn#1]
Hi @Doridian,

First of all, I really like the concept of "VPN over WebSocket", so I tried to run this project, but it doesn't seem to work properly. Is this project a complete project? Or is it an experiment?

I used this project as the VPN server, and then I wrote an iOS App myself as the VPN client.

![IMG_0050](https://user-images.githubusercontent.com/5037285/69937984-104af380-1517-11ea-8937-4a297950111c.PNG)

The server program is stuck [here](https://github.com/Doridian/wsvpn/blob/master/shared/socketHandler.go#L188), that is, all IP packets read from the client TUN disappeared after being written to the server TUN, and the server program unable to read any IP packets from the server TUN.

All IP packets read from the client TUN have the same source IP and are assigned [here](https://github.com/Doridian/wsvpn/blob/4622e6b3318fdcdda50ba06e13489d5dda456206/server/main.go#L206). This seems fine.

So, do you have any idea about the problem I encountered?

I'm not good at the VPN technique, so I really hope to get some suggestions from you, thank you! 😊

**Comment by Doridian** [comment]
The project is nothing I would call completed, but it does fully work and I was using it in both TUN and TAP modes personally (with itself as the client and server, never tested iOS as I don't have an Apple device).
It might have bugs that I didn't encounter, however.

If you need any more help, just let me know. If you closed the issue because you managed to fix it, also feel free to let me know that :)

**Comment by aofei** [comment]
Thanks for your reply, I closed this issue because I found the solution (from [here](https://community.openvpn.net/openvpn/wiki/BridgingAndRouting)). And I implemented my own server program by studying this project (see [this](https://gist.github.com/aofei/563636c7cca9eceef403bb9983e4f190)). Thank you very much! 😊
