### ISSUE TITLE
Is there a way to force WSVPN to use only TLS 1.3 and a particular cipher?

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#11]
Hi Mark,

Is there a way to force WSVPN to use only TLS 1.3 and use a particular TLS 1.3 only cipher such as TLS_CHACHA20_POLY1305_SHA256.    

CHACHA20_POLY1305 is also used by Wireguard and is the fastest cipher on basic embedded general purpose CPU.

**Comment by Doridian** [comment]
No way to configure this, yet. Will look into this soon.

**Comment by Doridian** [comment]
It seems golang decided to not support configuring TLS 1.3 ciphers at all: https://github.com/golang/go/issues/29349

There seems to be hacky ways around this, such as: https://www.joeshaw.org/abusing-go-linkname-to-customize-tls13-cipher-suites/
However I am unsure if I want to implement such a hacky fix.

Another possible solution would be to make "PreferServerCipherSuites" configurable in which case hopefully golang is smart enough to prefer the fastest cipher, so that is pretty easy to add (on server only of course).
Enforcing a certain minimum and maximum TLS version is also easy to add (both on server and client).

**Comment by vochong** [comment]
Please make TLS version min/max configurable but make TLS 1.3 the default TLS version.

Chacha20_Poly1305 is not always the best choice.   If both WSVPN client and server run on devices with newer CPUs (e.g. those with Intel AES-NI), AES-GCM will beat Chacha20_Poly1305. 

However, since the more common use case for WSVPN is to run the server on always-on low power embedded devices such as OpenWrt routers or RPI, Chacha20_Poly1305 would be the best choice for it.   Hopefully your approach of making PreferServerCipherSuites configurable on server would automatically let it pick the fastest cipher depending on the hardware on which the server runs.

You rock!  and I really mean it.

**Comment by Doridian** [comment]
I added a new option for being able to, a bit less hacky, adjust some cipher things.
`-tls-min-version` and `-tls-max-version` on both server and client
Also `-tls-cipher-preference` which accepts `AES` and `CHACHA` also on both server and client. This will not disable other ciphers, but simply prefer either AES based or ChaCha based ciphers.
Best I can do, and even that required something that isn't officially supported.

**Comment by Doridian** [comment]
Also on a side note: This setting should not be necessary. Golang is supposed to prefer ChaCha unless both sides support AES hardware acceleration.

**Comment by vochong** [comment]
Thanks so much Mark.   Your new enhancements work perfectly.  My r7800 router serving as WSVPN server went from around 49Mbps to 65Mbps  (using  TLS 1.3 / CHACHA).  A very nice speed increase.

I know a lot of engineers but have never seen an engineer as awesome and quick as you are.  Not only that, you are very helpful and willing to spend time to create and keep improving such a great piece of open-source software.  Kudos to you!
