### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rezaf28** [Doridian/wsvpn#148]
Hi
First of all, I would like to thank you for continuing this project.

I have a few general requests from you:
1- Make a road map
2- Documenting the content (your wiki is really awful)
3- Adding a wallet account to support more (you can ask for money against their request)
4- Adding additional explanations to the readme, for example, does it support udp in full?, icmp ping supported? Etc
********************************************************************
And some personal requests:
1- In addition to adding the Api system, which will cause serious security problems later, use radius, which is much better and more compatible with other services (for example, Mikrotik uses it in its operating system) and you can easily access project, because github is full of these radius libraries. And managers can control their customers more easily.
2- The most usage statistics of vpn are Android operating systems, of course, I know you don't have time for it, but you can use compatibility with Gomobile to release appropriate builds.
3- Today, censorship is done on a new platform and it is not the same as before, and even governments can block new methods such as Trojan-go and vless, planning to bypass new methods can be effective.
4- Never leave the project even when threatened!

I know my content was repetitive and boring, but I wanted to remind you again and also thank you.

**Comment by Doridian** [comment]
1) Since I track "the future" using GitHub issues, and there is currently almost no requests, there is no road map (since it would just be empty)
2) I know my documentation is not great, it is something I am not good at. I will gladly welcome anyone in writing documentation, and help them out with their questions
3) Will think about that
4) As for the explanations, I will think about a way to add it. To your question(s): In TUN mode it supports anything IP (TCP, ICMP, UDP, ...), in TAP mode it supports anything Ethernet (ARP, IP, IPv6, etc). WSVPN itself does not interfere or tamper with packets traveling through it beyond figuring out where they should go.

As for your personal requests:
1) I have created https://github.com/Doridian/wsvpn/issues/154 to track this
2) I will check on that, not heard of Gomobile before
3) WSVPN is not intended as a tool to bypass censorships. Due to the fact it uses standard web protocols, it may be able to do such by looking like normal browser traffic. Other tools, like what Tor uses with its many extensions, or things like naiveproxy, all have their niches, and WSVPN is explicitly aimed at working through the common HTTP stack and CDNs that we have in the internet today to make setting up a VPN and, say, tunneling your VPN through a CDN, is easy. To be clear: I fully support use-cases where WSVPN is used to fight censorship, but it is not something I have spent a majority of my time and research for WSVPN on.
4) Not planning on giving up on this!
