### ISSUE TITLE
Enhancement request: allow the ability to set the specific path to .htpasswd file

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#17]
Similar to the flags -tls-cert, --tls-key for the server, or -auth-file, --ca-certificates for the client,   users should be allowed to specify the path to the .htpasswd file on the server if the htpasswd authenticator is used.  This helps with scripting without having to change to the path of wsvpn binary.   Also, the server should expect a .htpasswd instead of htpasswd (to make it consistent with common practice).

For example:

./wsvpn_server_arm:
  -authenticator string
    	Which authenticator to use (allow-all, htpasswd)   <-- currently
    	Which authenticator to use (allow-all, path to .htpasswd file) (default "allow-all")    <--- enhancement

AUTH_FILE=/root/secrets/.htpasswd
/root/wsvpn/wsvpn_server_arm --authenticator $AUTH_FILE

**Comment by Doridian** [comment]
As this is a config option for a specific authenticator, I have to think of a way to make this less special, and in a way it would work with other, future, authenticators as well.
Will think about it.

**Comment by Doridian** [comment]
Added `--authenticator-config=FILE`. For htpasswd this is the htpasswd file, the name is just kept generic to work with any possible authenticator that needs a config file. The default filename for the htpasswd authenticator is still htpasswd (without the dot), because now you can specify `.htpasswd` yourself if you need it do be a dotfile
