### ISSUE TITLE
Questions regarding MTU setting

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#26]
Hi Mark,

Is there any reason why you set the default MTU to 1280 bytes?   During my testing, I can set it as high as 2000 bytes and such setting provides the best throughput.

When you plan to make any change or fix later, maybe the "ca"  key under cilent tls should also be changed to "server-ca" to make it self-explanatory as that of the server tls.

server:
tls:
    client-ca

client:
  tls:
    ca:       <--- change it to "server-ca" ?

**Comment by Doridian** [comment]
Might rename the CA entry, will think about it.

As for the default MTU? Because it is a safe default. In general, any value here (up to 65535) should work as WebSocket will gladly fragment the package for you. WebTransport that is another story, it will fail because it cannot fragment datagrams for you.
However, even with WebSocket, values that cause packet fragmentation (as in, an MTU where the payload causes the production of a WebSocket frame that does not fit in a single ethernet frame) can cause very bad performance issues on connections that have any packet loss (essentially, they cause the TCP-in-TCP problem to worsen).
The choice of 1280 specifically is because that is the lowest MTU suggested (and the lowest that supports IPv6) and safe in most encapsulations (PPPoE, VLANs, etc).
Lots of setups, especially in corporate environments and mobile networks with lots of tunneling layers and no support for jumbo frames, benefit from this small MTU in terms of reliability.
