### ISSUE TITLE
Enhancement request: add the setting to allow WSVPN client to keep trying to connect to server after a connect timeout.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#32]
Please add a client setting that allows it to keep retrying (forever or for a specified number of attempts) to connect to the server after a connect timeout (e.g. due to connectivity problem or server down).

Currently:

./client
panic: dial tcp [x.x.x.x]:8443: connect: connection timed out
goroutine 1 [running]:
main.main()
	/home/runner/work/wsvpn/wsvpn/client/main.go:112 +0x950

**Comment by Doridian** [comment]
Good idea, will see about implementing auto-(re)-connect.

For now, on Linux or macOS, you can use a shell script for this. Something like `while :; do ./client; sleep 5; done` (replace 5 with the number of seconds to wait between connection attempts)

**Comment by Doridian** [comment]
Added in 3.10.0 -> client.auto-reconnect-delay.
It can not limit the number of attempts right  now, quite simply because for that I first need to be able to determine what is a failed and what is a successful connection attempt.
Otherwise, say you set it to 3, then the client connects on the second attempt, but then the server restarts and the client will just immediately try attempt 3, fail, and exit.
So the only good way to limit attempts is to limit consecutive failed attempts only.

Right now my idea is "have gotten a full handshake from server and initialized the network interface with IP etc"

**Comment by vochong** [comment]
The new version 3.10.0 works great.  Prior to the new enhancement, I had to periodically (as part of a cron job) run a script that starts the wsvpn client and adds specific routes whenever the tun interface was up (I don't use the default route setting in the client.yml), because the wsvpn client would quit if my wsvpn server is down.   Thanks a lot.
