### ISSUE TITLE
cannot add tap into a linux bridge

### ISSUE THREAD

**Issue by limbo127** [Doridian/wsvpn#423]
Hello, 
when i'm trying to put a tap from client to a linux bridge, and some some traffic, for example dhpcp-client or arp  : 
2023/12/18 09:09:27 commands.go:82: [CLIENT-UNSET] Got reply to command ID 10ce7e8b-977a-4b62-aa32-ebff1f3223a8 (ok): OK
2023/12/18 09:09:27 commands.go:67: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Network mode TAP, Subnet 192.168.3.2/24, MTU 1280, IPConfig enabled
2023/12/18 09:09:27 commands.go:85: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Opened interface tap0
2023/12/18 09:09:27 commands.go:116: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Configured interface, VPN online
2023/12/18 09:09:52 ping.go:37: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Sent ping
2023/12/18 09:09:52 ping.go:13: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Received pong
2023/12/18 09:10:17 ping.go:37: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Sent ping
2023/12/18 09:10:17 ping.go:13: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Received pong
2023/12/18 09:10:42 ping.go:37: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Sent ping
2023/12/18 09:10:42 ping.go:13: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Received pong

2023/12/18 09:11:07 ping.go:37: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Sent ping
2023/12/18 09:11:12 ping.go:45: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Ping timeout
2023/12/18 09:11:12 base.go:285: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Adapter ERROR: stream canceled with error code 1
2023/12/18 09:11:12 vpnnet.go:48: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Error reading packet from tun: read tun: file already closed

client close
Regards, 
Nicolas

**Comment by Doridian** [comment]
The
```
 2023/12/18 09:11:12 ping.go:45: [CLIENT-f9362d80-8eb5-4016-a37c-3687987ac8e6] Ping timeout
```
seems weird. Usually that only happens when the network link breaks down.

This can happen if you try to route all packets through the VPN for example, which will then also route VPN traffic through the VPN, which will break your network. (It can also happen if you just route some subnets through the VPN that happen to contain the VPN server). Maybe add a route for just the VPN server's IP just to make sure.

Other than that, are you adding the VPN adapter to its own bridge? Or a bridge that has, say, your default network on it? I don't know if the VPN will work well if its adapter is on the bridge it has to route through

**Comment by limbo127** [comment]
Hello,
I just make a linux bridge or openvswitch bridge, start wsvpn, berify
that's ok with tunnel, then put the tun interface into bridge, then issue
appears.

Le jeu. 28 déc. 2023 à 19:17, Mark Dietzer ***@***.***> a
écrit :
