### ISSUE TITLE
Docker images do not support script usage

### ISSUE THREAD

**Issue by nemethf** [Doridian/wsvpn#57]
I wonder what is the indention behind creating the simple docker image as they only contain the go binaries.  Should they be used by setting the scripts.up/down in the config and mounting the scripts themselves into the containers?  

Based on the Dockerfile of the testcontainer and the output of `ldd $(which ip)` I was able to use the sever container with the following:
```
docker run --rm --cap-add=NET_ADMIN \
       -v `pwd`/config:/config \
       --device /dev/net/tun:/dev/net/tun \
       -v "/dev/net/tun:/dev/net/run" \
       -v /bin:/bin:ro \
       -v /lib64:/lib64:ro \
       -v /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:ro \
       -v /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro \
       -p 9000:9000/udp \
       ghcr.io/doridian/wsvpn/server:4.7.0
``` 
But it kind of defeats the purpose of containerization.

Thanks.

**Comment by Doridian** [comment]
I have to be honest, I never thought about using scripts with the Docker images. (I run WSVPN a lot without scripts and just "by itself").
I think I will change the images to be Alpine based, which should still keep them small, but will allow things to actually run.

Once this is done, as for how to use them, you have two possibilities:
1. Build upon my Docker images (`FROM ghcr.io/doridian/wsvpn/server:latest` etc)
2. Mount the scripts into the container, either just inside the `/config` volume or otherwise
