### ISSUE TITLE
Make wsvpn command line options to be POSIX-compliant.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#9]
This is just a cosmetic enhancement request to make WSVPN even more perfect :-).  I've been so happy discovering your awesome program when wandering around on github.

POSIX guideline:   https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

Use the prefix "--" instead of "-" for all command line options that have more than 1 character (e.g. -P  but --proxy).

Usage of ./wsvpn_server_arm:
  --authenticator string
    	Which authenticator to use (allow-all, htpasswd) (default "allow-all")
  --client-to-client
    	Allow client-to-client communication (in TAP)
  --listen string
    	Listen address for the WebSocket interface (default "127.0.0.1:9000")

etc.

**Comment by Doridian** [comment]
After learning more about golang's `flag` package, I found out it does indeed support using POSIX-style flags out of the box.
However, the auto-generated help sadly does not reflect such usage, see below:

```
PS C:\Users\Doridian\Programming\wsvpn> .\client.exe --connect ws://example.net
2022/06/10 08:55:55 Connecting to ws://example.net without authentication
PS C:\Users\Doridian\Programming\wsvpn> .\client.exe --connect=ws://example.net
2022/06/10 08:55:58 Connecting to ws://example.net without authentication
```

So since this usage works, I will  "downgrade" this issue to a documentation fix, which I will fix once I have written a comprehensive README.

**Comment by Doridian** [comment]
With config files, this seems unnecessary
